# Generated by Django 2.1.4 on 2019-01-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastGameVal', models.IntegerField(default=-1)),
                ('lastHRDate', models.DateTimeField(verbose_name='lastHRDate')),
            ],
        ),
    ]
